version: "3"

services:
  mysql:
    build:
      context: ./db
    ports:
      - 3306:3306
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64
  phpfpm:
    build:
      context: ./app
    volumes:
      - ../src:/work/backend
  nginx:
    build:
      context: ./web
    ports:
      - 80:80
    volumes:
      - ../src:/work/backend
      - ./web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: ['phpfpm']